"""Add due_date to CreditCard

Revision ID: 18eefeceed85
Revises: 330694bc884c
Create Date: 2024-12-15 12:59:40.002917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18eefeceed85'
down_revision = '330694bc884c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
