"""Add exclude_from_projections to Bill and CreditCard models

Revision ID: 330694bc884c
Revises: 
Create Date: 2024-12-15 00:31:42.817677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330694bc884c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_from_projections', sa.Boolean(), nullable=True))

    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_from_projections', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('exclude_from_projections')

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('exclude_from_projections')

    # ### end Alembic commands ###
