"""Add due_date to CreditCard model

Revision ID: 827620504b31
Revises: 18eefeceed85
Create Date: 2024-12-15 13:01:21.312477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827620504b31'
down_revision = '18eefeceed85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
